### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by nghiabtc** [Widiskel/t3rn-bridge-bot#2]
i used your code. and recently i found out that i lost my linked wallet assets, which never happened before. when i checked the codes again i found out that only your code was encrypted and could not be decrypted. this means that your bad code might have stolen my linked wallet assets.
if so then you are trash..

**Comment by Widiskel** [comment]
then don't use bot, im just encrypt my code so no one will stole it.
if your wallet drained check again what project you join so far, what dapps you connected, what transaction with approval that you approve, and what node you run with your PK. im always give an instruction to use new wallet so if your wallet drained, that not because of my bot.

**Comment by Josh589** [comment]
Hey....my test tokens are being sent to another wallet why? ...hope my waller is safe
